genome: "data/GCF_000721785.1_Aureobasidium_pullulans_var._pullulans_EXF-150_assembly_version_1.0_genomic.fna"
gff: "data/GCF_000721785.1_Aureobasidium_pullulans_var._pullulans_EXF-150_assembly_version_1.0_genomic.gff"
protein: "data/alfa_nb_linker_mscarlet_protein.fasta"

run:
  id: "Run_4"


ga:
  mode: "scalar"   # scalar | pareto
  pareto_top_k: 10
  population_size: 120
  generations: 10000
  mutation_rate: 0.07
  mutation_rate_final: 0.02
  elite_size: 10
  crossover_rate: 0.75
  tournament_size: 4
  immigrant_rate: 0.05
  early_stop_patience: 1000
  min_improvement: 1.0e-10
  random_seed: 42

fitness:
  alpha: 0.7
  beta: 0.3

gc:
  use_genome_target: true
  target: 0.52   # fallback when genome target cannot be computed
  sigma: 0.05

splice:
  donor_penalty: 0.8
  intron_penalty: 0.9
  intron_min_distance: 20
  intron_max_distance: 200

snapshot:
  count: 10

fungal:
  splice_penalty_weight: 5
  polyA_penalty_weight: 3
  structure_penalty_weight: 4
  gc_window: 50
  low_gc: 0.30
  high_gc: 0.70
  polya_motifs: ["AATAAA", "ATTAAA"]
  donor_motifs: ["AGGT", "CAGGT", "AAGGT", "GTATGT"]
